apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lq67ybq2r-dotnet-basic
  janus-idp.io/tekton: lq67ybq2r-dotnet-basic
  backstage.io/kubernetes-id: lq67ybq2r-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lq67ybq2r-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
